// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CPAtencionalclienteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/main/resources/chromedriver.exe");
    driver = new ChromeDriver();

  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cPAtencionalcliente() {
    driver.get("http://automationpractice.com/index.php?controller=contact");
    driver.manage().window().setSize(new Dimension(732, 680));
    driver.findElement(By.linkText("Sign in")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("matiasro02@hotmail.com");
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.id("passwd")).sendKeys("Bios2019");
    driver.findElement(By.cssSelector("#SubmitLogin > span")).click();
    driver.findElement(By.linkText("Contact us")).click();
    driver.findElement(By.id("id_contact")).click();
    {
      WebElement dropdown = driver.findElement(By.id("id_contact"));
      dropdown.findElement(By.xpath("//option[. = 'Customer service']")).click();
    }
    driver.findElement(By.id("id_contact")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("message")).click();
    driver.findElement(By.id("message")).sendKeys("Prueba mensaje, atencion al cliente, con exito.");
    driver.findElement(By.cssSelector("#submitMessage > span")).click();
    assertThat(driver.findElement(By.cssSelector(".alert")).getText(), is("Your message has been successfully sent to our team."));
    assertThat(driver.findElement(By.cssSelector(".alert")).getText(), is("Your message has been successfully sent to our team."));
    driver.findElement(By.linkText("Sign out")).click();
  }
}
